Reduce cli to min again because of (? don't know what's happening)
Run azure/CLI@v1
Starting script execution via docker image mcr.microsoft.com/azure-cli:latest
Error: Error: docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.

cleaning up container...
Warning: Error: No such container: MICROSOFT_AZURE_CLI_1619685531363_CONTAINER